name: fwfh_chewie
version: 0.7.0+2
description: WidgetFactory extension to render VIDEO with the chewie plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=2.5.0"
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  chewie: #^1.0.0
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ">=0.8.0 <0.10.0"
#  video_player:
#    git:
#      url: https://github.com/pf2707/flutter_plugins.git
#      ref: master
#      path: packages/video_player/video_player

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core
  fwfh_text_style:
    path: ../fwfh_text_style

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any
  plugin_platform_interface: any
#  video_player_platform_interface:
